/* 読み上げに使う声のファイル（tools/make_voice.py が自動で作る。手で直さない）
 * 文がこの表とぴったり同じとき（空白のちがいは気にしない）に、この音声を使う。無い文はブラウザが読み上げる。
 * 「nyu:」で はじまるものは ニューちゃんの 声。 */
window.G = window.G || {};

G.VOICE_CLIPS = {
  "にゃっほー！ きょうも おりょうり する ニャー！": 'assets/voice/m_greetDaily.m4a',
  "おかえり！ また いっしょに つくろう ニャー": 'assets/voice/m_greetAgain_1.m4a',
  "にゃっほー！ キッチンに きた ニャー！": 'assets/voice/m_greetAgain_2.m4a',
  "なにを つくろう ニャー？": 'assets/voice/m_content_1.m4a',
  "エプロン、 きもちが ひきしまる ニャー": 'assets/voice/m_content_3.m4a',
  "いい においが すると しあわせ ニャー〜": 'assets/voice/m_content_4.m4a',
  "ゴロゴロ ニャー…": 'assets/voice/m_pet_1.m4a',
  "きもちいい ニャー〜": 'assets/voice/m_pet_2.m4a',
  "うふふ、 くすぐったい ニャー": 'assets/voice/m_pet_3.m4a',
  "したの フライパンを おして ニャー！": 'assets/voice/m_cookHint.m4a',
  "キッチンに きた！ おりょうり する ニャー！": 'assets/voice/m_fromOsewa.m4a',
  "おうちに かえる ニャー！": 'assets/voice/m_goHomeNone.m4a',
  "インターネットに つながって いるときに かえる ニャー": 'assets/voice/m_offlineHome.m4a',
  "まかせて ニャー！": 'assets/voice/m_acceptRequest.m4a',
  "もうすこし まってね。 いま じゅんびちゅう ニャー！": 'assets/voice/m_comingSoon.m4a',
  "なにを つくる ニャー？": 'assets/voice/m_pickRecipe.m4a',
  "ざいりょうを あつめる ニャー！": 'assets/voice/m_gatherIntro.m4a',
  "れいぞうこと たなから だす ニャー": 'assets/voice/m_gatherHint.m4a',
  "それは こんど つかう ニャー": 'assets/voice/m_gatherWrong.m4a',
  "ぜんぶ そろった ニャー！": 'assets/voice/m_gatherDone.m4a',
  "ごはんを よそう ニャー！": 'assets/voice/m_scoopIntro.m4a',
  "なかの ぐは どれに する ニャー？": 'assets/voice/m_fillingIntro.m4a',
  "ぎゅっ ぎゅっと にぎる ニャー！": 'assets/voice/m_shapeIntro.m4a',
  "のりを まく ニャー！": 'assets/voice/m_wrapIntro.m4a',
  "パンに バターを ぬる ニャー！": 'assets/voice/m_spreadIntro.m4a',
  "すきな ぐを はさむ ニャー！": 'assets/voice/m_fillIntro.m4a',
  "できたら チェックを おして ニャー": 'assets/voice/m_readyCheck.m4a',
  "てんせんに そって きる ニャー！": 'assets/voice/m_cutIntro.m4a',
  "ほんとうの ほうちょうは、 おとなの ひとと いっしょに つかう ニャー！": 'assets/voice/m_safetyKnife.m4a',
  "ほんとうの ひは、 おとなの ひとと いっしょに つかう ニャー！": 'assets/voice/m_safetyFire.m4a',
  "たまごを こつん ニャー！": 'assets/voice/m_crackIntro.m4a',
  "ぐるぐる まぜまぜ ニャー〜": 'assets/voice/m_mixIntro.m4a',
  "コンロの つまみを おして ニャー！": 'assets/voice/m_fryIntro.m4a',
  "ジュージュー… いい におい ニャー〜": 'assets/voice/m_frySizzle.m4a',
  "いい におい！ いまが ちょうどいい ニャー！": 'assets/voice/m_fryReady.m4a',
  "えいっと ひっくりかえす ニャー！": 'assets/voice/m_flipIntro.m4a',
  "くるっ！ じょうず ニャー！": 'assets/voice/m_flipDone.m4a',
  "いいかんじ ニャー！": 'assets/voice/m_cheer_1.m4a',
  "じょうず ニャー！": 'assets/voice/m_cheer_2.m4a',
  "その ちょうし ニャー！": 'assets/voice/m_cheer_3.m4a',
  "できた ニャー！": 'assets/voice/m_stepDone_1.m4a',
  "ばっちり ニャー！": 'assets/voice/m_stepDone_2.m4a',
  "おみずで きれいに あらう ニャー！": 'assets/voice/m_washIntro.m4a',
  "こねこね、 まるく する ニャー！": 'assets/voice/m_kneadIntro.m4a',
  "ぺたぺた、 かたちを つくる ニャー！": 'assets/voice/m_patIntro.m4a',
  "ごはんを ちいさく にぎる ニャー！": 'assets/voice/m_sushiIntro.m4a',
  "めんぼうで のばす ニャー！": 'assets/voice/m_rollIntro.m4a',
  "すきな ところを かたぬき する ニャー！": 'assets/voice/m_cutoutIntro.m4a',
  "ソースを ぬりぬり ニャー！": 'assets/voice/m_sauceSpread.m4a',
  "クリームを ぬりぬり ニャー！": 'assets/voice/m_creamSpread.m4a',
  "オーブンに いれる ニャー！": 'assets/voice/m_ovenIntro.m4a',
  "やけるまで まつ ニャー〜": 'assets/voice/m_ovenWait.m4a',
  "チン！ やけた ニャー！": 'assets/voice/m_ovenDone.m4a',
  "おなべを ぐるぐる まぜる ニャー！": 'assets/voice/m_boilIntro.m4a',
  "ぐつぐつ、 いい におい ニャー！": 'assets/voice/m_boilDone.m4a',
  "れいぞうこで ひやす ニャー！": 'assets/voice/m_chillIntro.m4a',
  "ひえひえ！ かたまった ニャー！": 'assets/voice/m_chillDone.m4a',
  "カップに いれる ニャー！": 'assets/voice/m_pourIntro.m4a',
  "ごはんに かける ニャー！": 'assets/voice/m_pourOverIntro.m4a',
  "くるくる まく ニャー！": 'assets/voice/m_rollupIntro.m4a',
  "フライがえしで まぜる ニャー！": 'assets/voice/m_stirIntro.m4a',
  "ちょっと あじみ… ぺろり！ おいしい ニャー！": 'assets/voice/m_taste.m4a',
  "すきな ものを のせて かざる ニャー！": 'assets/voice/m_decoIntro.m4a',
  "ソースで おえかき も できる ニャー！": 'assets/voice/m_sauceIntro.m4a',
  "きれいに ふいた ニャー": 'assets/voice/m_decoClear.m4a',
  "どれを きる ニャー？": 'assets/voice/m_dressIntro.m4a',
  "じゃーん！ にあってる ニャー？": 'assets/voice/m_dressDone.m4a',
  "つくった おりょうりの しゃしん ニャー！": 'assets/voice/m_bookIntro.m4a',
  "まだ つくって いない ニャー": 'assets/voice/m_bookNotYet.m4a',
  "この しゃしん、 けす ニャー？": 'assets/voice/m_photoDelete.m4a',
  "しゃしん パチリ！ レシピちょうに のこす ニャー！": 'assets/voice/m_photoSaved.m4a',
  "ニューちゃんの ところへ はこぶ ニャー！": 'assets/voice/m_carry.m4a',
  "わたしも いっしょに たべる ニャー！": 'assets/voice/m_together.m4a',
  "おりょうり、 やめる ニャー？": 'assets/voice/m_quitAsk.m4a',
  "きょうは ここまで。 また あした ニャー": 'assets/voice/m_limit.m4a',
  "また いっしょに つくろう ニャー！": 'assets/voice/m_bye.m4a',
  "シールを もらった ニャー！": 'assets/voice/m_stickerGet.m4a',
  "あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlockRecipe.m4a',
  "あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlockDress.m4a',
  "あたらしい おさらが ふえた ニャー！": 'assets/voice/m_unlockPlate.m4a',
  "プレゼントが とどいた ニャー！": 'assets/voice/m_giftRecipe.m4a',
  "きょうの ごあいさつ ニャー": 'assets/voice/m_dailyHeart.m4a',
  "nyu:えへへ、 くすぐったい ニャー": 'assets/voice/n_pet_1.m4a',
  "nyu:きもちいい ニャー〜": 'assets/voice/n_pet_2.m4a',
  "nyu:もっと なでて ニャー！": 'assets/voice/n_pet_3.m4a',
  "もどる": 'assets/voice/g_back.m4a',
  "やったね": 'assets/voice/g_yatta.m4a',
  "またね": 'assets/voice/g_bye.m4a',
  "はじめに もどる": 'assets/voice/g_again.m4a',
  "はじめる": 'assets/voice/g_start.m4a',
  "ぜんぶ あつめたよ！": 'assets/voice/g_stickers_all.m4a'
};
