/* 読み上げに使う声のファイル（tools/make_voice.py が自動で作る。手で直さない）
 * 文がこの表とぴったり同じとき（空白のちがいは気にしない）に、この音声を使う。無い文はブラウザが読み上げる。
 * 「nyu:」で はじまるものは ニューちゃんの 声。 */
window.G = window.G || {};

G.VOICE_CLIPS = {
  "にゃっほー！ きょうも おりょうり する ニャー！": 'assets/voice/m_greetDaily.m4a',
  "おかえり！ また いっしょに つくろう ニャー": 'assets/voice/m_greetAgain_1.m4a',
  "にゃっほー！ キッチンに きた ニャー！": 'assets/voice/m_greetAgain_2.m4a',
  "なにを つくろう ニャー？": 'assets/voice/m_content_1.m4a',
  "ニューちゃんに おいしいの つくって あげる ニャー！": 'assets/voice/m_content_2.m4a',
  "エプロン、 きもちが ひきしまる ニャー": 'assets/voice/m_content_3.m4a',
  "いい においが すると しあわせ ニャー〜": 'assets/voice/m_content_4.m4a',
  "ゴロゴロ ニャー…": 'assets/voice/m_pet_1.m4a',
  "きもちいい ニャー〜": 'assets/voice/m_pet_2.m4a',
  "うふふ、 くすぐったい ニャー": 'assets/voice/m_pet_3.m4a',
  "したの フライパンを おして ニャー！": 'assets/voice/m_cookHint.m4a',
  "キッチンに きた！ おりょうり する ニャー！": 'assets/voice/m_fromOsewa.m4a',
  "おうちに かえる ニャー！": 'assets/voice/m_goHomeNone.m4a',
  "ハートを もって かえる ニャー！": 'assets/voice/m_goHomeHearts.m4a',
  "ハートを もっと ためたら つくれる ニャー！": 'assets/voice/m_lockRecipe.m4a',
  "ハートを もっと ためたら きられる ニャー！": 'assets/voice/m_lockDress.m4a',
  "インターネットに つながって いるときに かえる ニャー": 'assets/voice/m_offlineHome.m4a',
  "まかせて ニャー！": 'assets/voice/m_acceptRequest.m4a',
  "もうすこし まってね。 いま じゅんびちゅう ニャー！": 'assets/voice/m_comingSoon.m4a',
  "なにを つくる ニャー？": 'assets/voice/m_pickRecipe.m4a',
  "ざいりょうを あつめる ニャー！": 'assets/voice/m_gatherIntro.m4a',
  "れいぞうこと たなから だす ニャー": 'assets/voice/m_gatherHint.m4a',
  "それは こんど つかう ニャー": 'assets/voice/m_gatherWrong.m4a',
  "ぜんぶ そろった ニャー！": 'assets/voice/m_gatherDone.m4a',
  "ごはんを よそう ニャー！": 'assets/voice/m_scoopIntro.m4a',
  "なかの ぐは どれに する ニャー？": 'assets/voice/m_fillingIntro.m4a',
  "ぎゅっ ぎゅっと にぎる ニャー！": 'assets/voice/m_shapeIntro.m4a',
  "のりを まく ニャー！": 'assets/voice/m_wrapIntro.m4a',
  "パンに バターを ぬる ニャー！": 'assets/voice/m_spreadIntro.m4a',
  "すきな ぐを はさむ ニャー！": 'assets/voice/m_fillIntro.m4a',
  "できたら チェックを おして ニャー": 'assets/voice/m_readyCheck.m4a',
  "てんせんに そって きる ニャー！": 'assets/voice/m_cutIntro.m4a',
  "きるときは ねこの て ニャー！": 'assets/voice/m_nekoNoTe.m4a',
  "ほんとうの ほうちょうは、 おとなの ひとと いっしょに つかう ニャー！": 'assets/voice/m_safetyKnife.m4a',
  "ほんとうの ひは、 おとなの ひとと いっしょに つかう ニャー！": 'assets/voice/m_safetyFire.m4a',
  "たまごを こつん ニャー！": 'assets/voice/m_crackIntro.m4a',
  "ぐるぐる まぜまぜ ニャー〜": 'assets/voice/m_mixIntro.m4a',
  "コンロの つまみを おして ニャー！": 'assets/voice/m_fryIntro.m4a',
  "ジュージュー… いい におい ニャー〜": 'assets/voice/m_frySizzle.m4a',
  "いい におい！ いまが ちょうどいい ニャー！": 'assets/voice/m_fryReady.m4a',
  "えいっと ひっくりかえす ニャー！": 'assets/voice/m_flipIntro.m4a',
  "くるっ！ じょうず ニャー！": 'assets/voice/m_flipDone.m4a',
  "いいかんじ ニャー！": 'assets/voice/m_cheer_1.m4a',
  "じょうず ニャー！": 'assets/voice/m_cheer_2.m4a',
  "その ちょうし ニャー！": 'assets/voice/m_cheer_3.m4a',
  "できた ニャー！": 'assets/voice/m_stepDone_1.m4a',
  "ばっちり ニャー！": 'assets/voice/m_stepDone_2.m4a',
  "おみずで きれいに あらう ニャー！": 'assets/voice/m_washIntro.m4a',
  "こねこね、 まるく する ニャー！": 'assets/voice/m_kneadIntro.m4a',
  "ぺたぺた、 かたちを つくる ニャー！": 'assets/voice/m_patIntro.m4a',
  "ごはんを ちいさく にぎる ニャー！": 'assets/voice/m_sushiIntro.m4a',
  "めんぼうで のばす ニャー！": 'assets/voice/m_rollIntro.m4a',
  "すきな ところを かたぬき する ニャー！": 'assets/voice/m_cutoutIntro.m4a',
  "ソースを ぬりぬり ニャー！": 'assets/voice/m_sauceSpread.m4a',
  "クリームを ぬりぬり ニャー！": 'assets/voice/m_creamSpread.m4a',
  "オーブンに いれる ニャー！": 'assets/voice/m_ovenIntro.m4a',
  "やけるまで まつ ニャー〜": 'assets/voice/m_ovenWait.m4a',
  "チン！ やけた ニャー！": 'assets/voice/m_ovenDone.m4a',
  "おなべを ぐるぐる まぜる ニャー！": 'assets/voice/m_boilIntro.m4a',
  "ぐつぐつ、 いい におい ニャー！": 'assets/voice/m_boilDone.m4a',
  "れいぞうこで ひやす ニャー！": 'assets/voice/m_chillIntro.m4a',
  "ひえひえ！ かたまった ニャー！": 'assets/voice/m_chillDone.m4a',
  "カップに いれる ニャー！": 'assets/voice/m_pourIntro.m4a',
  "ごはんに かける ニャー！": 'assets/voice/m_pourOverIntro.m4a',
  "くるくる まく ニャー！": 'assets/voice/m_rollupIntro.m4a',
  "フライがえしで まぜる ニャー！": 'assets/voice/m_stirIntro.m4a',
  "ちょっと あじみ… ぺろり！ おいしい ニャー！": 'assets/voice/m_taste.m4a',
  "すきな ものを のせて かざる ニャー！": 'assets/voice/m_decoIntro.m4a',
  "ソースで おえかき も できる ニャー！": 'assets/voice/m_sauceIntro.m4a',
  "きれいに ふいた ニャー": 'assets/voice/m_decoClear.m4a',
  "どれを きる ニャー？": 'assets/voice/m_dressIntro.m4a',
  "じゃーん！ にあってる ニャー？": 'assets/voice/m_dressDone.m4a',
  "つくった おりょうりの しゃしん ニャー！": 'assets/voice/m_bookIntro.m4a',
  "まだ つくって いない ニャー": 'assets/voice/m_bookNotYet.m4a',
  "この しゃしん、 けす ニャー？": 'assets/voice/m_photoDelete.m4a',
  "しゃしん パチリ！ レシピちょうに のこす ニャー！": 'assets/voice/m_photoSaved.m4a',
  "ニューちゃんの ところへ はこぶ ニャー！": 'assets/voice/m_carry.m4a',
  "めしあがれ ニャー！": 'assets/voice/m_serve.m4a',
  "わたしも いっしょに たべる ニャー！": 'assets/voice/m_together.m4a',
  "おいしいね ニャー！": 'assets/voice/m_togetherYum.m4a',
  "おりょうり、 やめる ニャー？": 'assets/voice/m_quitAsk.m4a',
  "きょうは ここまで。 また あした ニャー": 'assets/voice/m_limit.m4a',
  "また いっしょに つくろう ニャー！": 'assets/voice/m_bye.m4a',
  "シールを もらった ニャー！": 'assets/voice/m_stickerGet.m4a',
  "あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlockRecipe.m4a',
  "あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlockDress.m4a',
  "あたらしい おさらが ふえた ニャー！": 'assets/voice/m_unlockPlate.m4a',
  "プレゼントが とどいた ニャー！": 'assets/voice/m_giftRecipe.m4a',
  "きょうの ごあいさつ ニャー": 'assets/voice/m_dailyHeart.m4a',
  "nyu:おねえちゃん、 おなか すいた ニャー！": 'assets/voice/n_hungry_1.m4a',
  "nyu:なにか つくって ニャー！": 'assets/voice/n_hungry_2.m4a',
  "nyu:きょうは この おりょうりが たべたい ニャー！": 'assets/voice/n_request.m4a',
  "nyu:えへへ、 くすぐったい ニャー": 'assets/voice/n_pet_1.m4a',
  "nyu:きもちいい ニャー〜": 'assets/voice/n_pet_2.m4a',
  "nyu:もっと なでて ニャー！": 'assets/voice/n_pet_3.m4a',
  "nyu:いい におい ニャー！": 'assets/voice/n_smell.m4a',
  "nyu:まだかな〜、 たのしみ ニャー！": 'assets/voice/n_wait_1.m4a',
  "nyu:わくわく ニャー！": 'assets/voice/n_wait_2.m4a',
  "nyu:おなか いっぱい。 ごちそうさま ニャー！": 'assets/voice/n_full.m4a',
  "nyu:わあ、 おいしそう ニャー！": 'assets/voice/n_peek.m4a',
  "nyu:あー！ おねえちゃん ずるい ニャー！": 'assets/voice/n_sneaky.m4a',
  "nyu:いただきます ニャー！": 'assets/voice/n_itadaki.m4a',
  "nyu:もぐもぐ ニャー…": 'assets/voice/n_munch_1.m4a',
  "nyu:はふはふ ニャー！": 'assets/voice/n_munch_2.m4a',
  "nyu:おいしい ニャー！": 'assets/voice/n_yum_1.m4a',
  "nyu:ほっぺが おちちゃう ニャー！": 'assets/voice/n_yum_2.m4a',
  "nyu:しあわせ ニャー〜": 'assets/voice/n_yum_3.m4a',
  "nyu:おえかき、 かわいい ニャー！": 'assets/voice/n_decoDraw.m4a',
  "nyu:もりもりで うれしい ニャー！": 'assets/voice/n_decoMany.m4a',
  "nyu:これ だいすき！ ありがとう ニャー！": 'assets/voice/n_favorite.m4a',
  "nyu:おねえちゃん、 おぼえてて くれた ニャー！": 'assets/voice/n_remember.m4a',
  "nyu:ごちそうさま ニャー！": 'assets/voice/n_gochiso.m4a',
  "nyu:やったー！ おねえちゃんと いっしょ ニャー！": 'assets/voice/n_togetherYay.m4a',
  "nyu:ふたりだと もっと おいしい ニャー！": 'assets/voice/n_togetherYum.m4a',
  "nyu:おなか いっぱい。 あとで たべる ニャー！": 'assets/voice/n_later.m4a',
  "nyu:おねえちゃん、 まってた ニャー！": 'assets/voice/n_welcome.m4a',
  "nyu:また たべに くる ニャー！": 'assets/voice/n_bye.m4a',
  "nyu:また つくってね ニャー！": 'assets/voice/n_byeHome.m4a',
  "もどる": 'assets/voice/g_back.m4a',
  "やったね": 'assets/voice/g_yatta.m4a',
  "またね": 'assets/voice/g_bye.m4a',
  "はじめに もどる": 'assets/voice/g_again.m4a',
  "はじめる": 'assets/voice/g_start.m4a',
  "ニャーちゃん おりょうりゲーム": 'assets/voice/g_title.m4a',
  "ぜんぶ あつめたよ！": 'assets/voice/g_stickers_all.m4a',
  "できた": 'assets/voice/g_draw_done.m4a',
  "つぎの ページ": 'assets/voice/g_page_next.m4a',
  "まえの ページ": 'assets/voice/g_page_prev.m4a',
  "いろ": 'assets/voice/g_clothes_color.m4a',
  "なし": 'assets/voice/g_ribbon_none.m4a',
  "ピンク": 'assets/voice/g_ribbon_pink.m4a',
  "ぼうし": 'assets/voice/g_acc_slot_head.m4a',
  "コックぼうし": 'assets/voice/g_acc_chefhat.m4a',
  "さんかくきん": 'assets/voice/g_acc_kerchief.m4a',
  "ベレーぼう": 'assets/voice/g_acc_beret.m4a',
  "ネコみみ バンダナ": 'assets/voice/g_acc_catband.m4a',
  "エプロン": 'assets/voice/g_clothes_apron.m4a',
  "チェックの エプロン": 'assets/voice/g_clothes_checkapron.m4a',
  "みずたまの エプロン": 'assets/voice/g_clothes_dotapron.m4a',
  "いちごの エプロン": 'assets/voice/g_clothes_strawapron.m4a',
  "おさかなの エプロン": 'assets/voice/g_clothes_fishapron.m4a',
  "にくきゅうの エプロン": 'assets/voice/g_clothes_pawapron.m4a',
  "コックさんの ふく": 'assets/voice/g_clothes_chefcoat.m4a',
  "まじょの エプロン": 'assets/voice/g_clothes_witchapron.m4a',
  "サンタの エプロン": 'assets/voice/g_clothes_santaapron.m4a',
  "ごはん": 'assets/voice/g_ing_rice.m4a',
  "のり": 'assets/voice/g_ing_nori.m4a',
  "しゃけ": 'assets/voice/g_ing_salmon.m4a',
  "おかか": 'assets/voice/g_ing_okaka.m4a',
  "ツナ": 'assets/voice/g_ing_tuna.m4a',
  "パン": 'assets/voice/g_ing_bread.m4a',
  "バター": 'assets/voice/g_ing_butter.m4a',
  "たまご": 'assets/voice/g_ing_egg.m4a',
  "きゅうり": 'assets/voice/g_ing_cucumber.m4a',
  "いちごジャム": 'assets/voice/g_ing_jam.m4a',
  "こむぎこ": 'assets/voice/g_ing_flour.m4a',
  "ぎゅうにゅう": 'assets/voice/g_ing_milk.m4a',
  "さとう": 'assets/voice/g_ing_sugar.m4a',
  "いちご": 'assets/voice/g_ing_strawberry.m4a',
  "バナナ": 'assets/voice/g_ing_banana.m4a',
  "ホイップ": 'assets/voice/g_ing_whip.m4a',
  "はちみつ": 'assets/voice/g_ing_honey.m4a',
  "ブルーベリー": 'assets/voice/g_ing_blueberry.m4a',
  "にんじん": 'assets/voice/g_ing_carrot.m4a',
  "とりにく": 'assets/voice/g_ing_chicken.m4a',
  "トマトソース": 'assets/voice/g_ing_tomatosauce.m4a',
  "おさかな": 'assets/voice/g_ing_fish.m4a',
  "だいこん": 'assets/voice/g_ing_daikon.m4a',
  "ブロッコリー": 'assets/voice/g_ing_broccoli.m4a',
  "チーズ": 'assets/voice/g_ing_cheese.m4a',
  "トマト": 'assets/voice/g_ing_tomato.m4a',
  "ピーマン": 'assets/voice/g_ing_greenpepper.m4a',
  "じゃがいも": 'assets/voice/g_ing_potato.m4a',
  "かぼちゃ": 'assets/voice/g_ing_pumpkin.m4a',
  "まぐろ": 'assets/voice/g_ing_tunafish.m4a',
  "サーモン": 'assets/voice/g_ing_salmonraw.m4a',
  "たい": 'assets/voice/g_ing_seabream.m4a',
  "アイシング": 'assets/voice/g_ing_icing.m4a',
  "おにぎり": 'assets/voice/g_recipe_onigiri.m4a',
  "サンドイッチ": 'assets/voice/g_recipe_sandwich.m4a',
  "ホットケーキ": 'assets/voice/g_recipe_pancake.m4a',
  "オムライス": 'assets/voice/g_recipe_omurice.m4a',
  "やきざかな": 'assets/voice/g_recipe_grillfish.m4a',
  "ピザ": 'assets/voice/g_recipe_pizza.m4a',
  "カレーライス": 'assets/voice/g_recipe_curry.m4a',
  "ハンバーグ": 'assets/voice/g_recipe_hamburg.m4a',
  "クッキー": 'assets/voice/g_recipe_cookie.m4a',
  "プリン": 'assets/voice/g_recipe_pudding.m4a',
  "おすし": 'assets/voice/g_recipe_sushi.m4a',
  "いちごの ケーキ": 'assets/voice/g_recipe_cake.m4a',
  "かぼちゃの パイ": 'assets/voice/g_recipe_pumpkinpie.m4a',
  "クリスマスケーキ": 'assets/voice/g_recipe_xmascake.m4a',
  "まるい おさら": 'assets/voice/g_plate_round.m4a',
  "しかくい おさら": 'assets/voice/g_plate_square.m4a',
  "ハートの おさら": 'assets/voice/g_plate_heart.m4a',
  "おさかなの おさら": 'assets/voice/g_plate_fish.m4a',
  "ネコの おさら": 'assets/voice/g_plate_cat.m4a',
  "おほしさまの おさら": 'assets/voice/g_plate_star.m4a',
  "めだまやき": 'assets/voice/g_sticker_03.m4a',
  "カレー": 'assets/voice/g_sticker_05.m4a',
  "ケーキ": 'assets/voice/g_sticker_09.m4a',
  "カップケーキ": 'assets/voice/g_sticker_16.m4a',
  "スプーン": 'assets/voice/g_sticker_18.m4a',
  "フォーク": 'assets/voice/g_sticker_19.m4a',
  "おほしさま": 'assets/voice/g_sticker_20.m4a',
  "シールちょう。 つぎの シールまで ハート あと 1こ": 'assets/voice/g_book_01.m4a',
  "シールちょう。 つぎの シールまで ハート あと 2こ": 'assets/voice/g_book_02.m4a',
  "シールちょう。 つぎの シールまで ハート あと 3こ": 'assets/voice/g_book_03.m4a',
  "シールちょう。 つぎの シールまで ハート あと 4こ": 'assets/voice/g_book_04.m4a',
  "シールちょう。 つぎの シールまで ハート あと 5こ": 'assets/voice/g_book_05.m4a',
  "シールちょう。 つぎの シールまで ハート あと 6こ": 'assets/voice/g_book_06.m4a',
  "シールちょう。 つぎの シールまで ハート あと 7こ": 'assets/voice/g_book_07.m4a',
  "シールちょう。 つぎの シールまで ハート あと 8こ": 'assets/voice/g_book_08.m4a',
  "シールちょう。 つぎの シールまで ハート あと 9こ": 'assets/voice/g_book_09.m4a',
  "シールちょう。 つぎの シールまで ハート あと 10こ": 'assets/voice/g_book_10.m4a',
  "シールを もらったよ！ おにぎり": 'assets/voice/m_get_sticker_01.m4a',
  "シールを もらったよ！ ホットケーキ": 'assets/voice/m_get_sticker_02.m4a',
  "シールを もらったよ！ めだまやき": 'assets/voice/m_get_sticker_03.m4a',
  "シールを もらったよ！ ピザ": 'assets/voice/m_get_sticker_04.m4a',
  "シールを もらったよ！ カレー": 'assets/voice/m_get_sticker_05.m4a',
  "シールを もらったよ！ クッキー": 'assets/voice/m_get_sticker_06.m4a',
  "シールを もらったよ！ プリン": 'assets/voice/m_get_sticker_07.m4a',
  "シールを もらったよ！ おすし": 'assets/voice/m_get_sticker_08.m4a',
  "シールを もらったよ！ ケーキ": 'assets/voice/m_get_sticker_09.m4a',
  "シールを もらったよ！ にんじん": 'assets/voice/m_get_sticker_10.m4a',
  "シールを もらったよ！ トマト": 'assets/voice/m_get_sticker_11.m4a',
  "シールを もらったよ！ チーズ": 'assets/voice/m_get_sticker_12.m4a',
  "シールを もらったよ！ たまご": 'assets/voice/m_get_sticker_13.m4a',
  "シールを もらったよ！ おさかな": 'assets/voice/m_get_sticker_14.m4a',
  "シールを もらったよ！ いちご": 'assets/voice/m_get_sticker_15.m4a',
  "シールを もらったよ！ カップケーキ": 'assets/voice/m_get_sticker_16.m4a',
  "シールを もらったよ！ ブロッコリー": 'assets/voice/m_get_sticker_17.m4a',
  "シールを もらったよ！ スプーン": 'assets/voice/m_get_sticker_18.m4a',
  "シールを もらったよ！ フォーク": 'assets/voice/m_get_sticker_19.m4a',
  "シールを もらったよ！ おほしさま": 'assets/voice/m_get_sticker_20.m4a',
  "つくる": 'assets/voice/g_home_cook.m4a',
  "おしゃれ": 'assets/voice/g_home_dress.m4a',
  "レシピ": 'assets/voice/g_home_book.m4a',
  "おうち": 'assets/voice/g_home_osewa.m4a',
  "おにぎりを つくる ニャー！": 'assets/voice/m_make_onigiri.m4a',
  "おにぎりを つくる": 'assets/voice/g_make_onigiri.m4a',
  "サンドイッチを つくる ニャー！": 'assets/voice/m_make_sandwich.m4a',
  "サンドイッチを つくる": 'assets/voice/g_make_sandwich.m4a',
  "ホットケーキを つくる ニャー！": 'assets/voice/m_make_pancake.m4a',
  "ホットケーキを つくる": 'assets/voice/g_make_pancake.m4a',
  "オムライスを つくる ニャー！": 'assets/voice/m_make_omurice.m4a',
  "オムライスを つくる": 'assets/voice/g_make_omurice.m4a',
  "やきざかなを つくる ニャー！": 'assets/voice/m_make_grillfish.m4a',
  "やきざかなを つくる": 'assets/voice/g_make_grillfish.m4a',
  "ピザを つくる ニャー！": 'assets/voice/m_make_pizza.m4a',
  "ピザを つくる": 'assets/voice/g_make_pizza.m4a',
  "カレーライスを つくる ニャー！": 'assets/voice/m_make_curry.m4a',
  "カレーライスを つくる": 'assets/voice/g_make_curry.m4a',
  "ハンバーグを つくる ニャー！": 'assets/voice/m_make_hamburg.m4a',
  "ハンバーグを つくる": 'assets/voice/g_make_hamburg.m4a',
  "クッキーを つくる ニャー！": 'assets/voice/m_make_cookie.m4a',
  "クッキーを つくる": 'assets/voice/g_make_cookie.m4a',
  "プリンを つくる ニャー！": 'assets/voice/m_make_pudding.m4a',
  "プリンを つくる": 'assets/voice/g_make_pudding.m4a',
  "おすしを つくる ニャー！": 'assets/voice/m_make_sushi.m4a',
  "おすしを つくる": 'assets/voice/g_make_sushi.m4a',
  "いちごの ケーキを つくる ニャー！": 'assets/voice/m_make_cake.m4a',
  "いちごの ケーキを つくる": 'assets/voice/g_make_cake.m4a',
  "かぼちゃの パイを つくる ニャー！": 'assets/voice/m_make_pumpkinpie.m4a',
  "かぼちゃの パイを つくる": 'assets/voice/g_make_pumpkinpie.m4a',
  "クリスマスケーキを つくる ニャー！": 'assets/voice/m_make_xmascake.m4a',
  "クリスマスケーキを つくる": 'assets/voice/g_make_xmascake.m4a',
  "オムライス！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_omurice.m4a',
  "やきざかな！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_grillfish.m4a',
  "ピザ！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_pizza.m4a',
  "カレーライス！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_curry.m4a',
  "ハンバーグ！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_hamburg.m4a',
  "クッキー！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_cookie.m4a',
  "プリン！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_pudding.m4a',
  "おすし！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_sushi.m4a',
  "いちごの ケーキ！ あたらしい レシピを おぼえた ニャー！": 'assets/voice/m_unlock_recipe_cake.m4a',
  "チェックの エプロン！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_checkapron.m4a',
  "みずたまの エプロン！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_dotapron.m4a',
  "いちごの エプロン！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_strawapron.m4a',
  "おさかなの エプロン！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_fishapron.m4a',
  "にくきゅうの エプロン！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_pawapron.m4a',
  "コックさんの ふく！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_chefcoat.m4a',
  "ベレーぼう！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_beret.m4a',
  "ネコみみ バンダナ！ あたらしい おしゃれが ふえた ニャー！": 'assets/voice/m_unlock_dress_catband.m4a',
  "ハートの おさら！ あたらしい おさらが ふえた ニャー！": 'assets/voice/m_unlock_plate_heart.m4a',
  "おさかなの おさら！ あたらしい おさらが ふえた ニャー！": 'assets/voice/m_unlock_plate_fish.m4a',
  "ネコの おさら！ あたらしい おさらが ふえた ニャー！": 'assets/voice/m_unlock_plate_cat.m4a',
  "おほしさまの おさら！ あたらしい おさらが ふえた ニャー！": 'assets/voice/m_unlock_plate_star.m4a',
  "ハロウィンの かぼちゃの パイ！ プレゼントが とどいた ニャー！": 'assets/voice/m_gift_pumpkinpie.m4a',
  "クリスマスの クリスマスケーキ！ プレゼントが とどいた ニャー！": 'assets/voice/m_gift_xmascake.m4a',
  "ハロウィンの まじょの エプロン！ プレゼントが とどいた ニャー！": 'assets/voice/m_gift_witchapron.m4a',
  "クリスマスの サンタの エプロン！ プレゼントが とどいた ニャー！": 'assets/voice/m_gift_santaapron.m4a',
  "じゅうがつに とどく ニャー！": 'assets/voice/m_when_pumpkinpie.m4a',
  "じゅうにがつに とどく ニャー！": 'assets/voice/m_when_xmascake.m4a',
  "つづける": 'assets/voice/g_say_8d495760.m4a',
  "やめる": 'assets/voice/g_say_18ca8614.m4a',
  "れいぞうこ": 'assets/voice/g_say_27653191.m4a',
  "ふきん": 'assets/voice/g_say_569da393.m4a',
  "キッチンに もどる": 'assets/voice/g_say_84e32fd0.m4a',
  "はい": 'assets/voice/g_say_c92b4cda.m4a',
  "けす": 'assets/voice/g_say_e85587b1.m4a'
};
